#spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://47.107.63.235:3307/gulimall_sms
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  application:
#    name: gulimall-coupon
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml   #classpath扫描当前类路径，classpath*扫描所有类路径
#  global-config:
#    db-config:
#      id-type: auto   #配置自增主键
#
#server:
#  port: 7000

